export default {
    // User
    LOGIN_REQUEST: '@@user/LOGIN_REQUEST',
    LOGIN_FAILURE: '@@user/LOGIN_FAILURE',
    LOGIN_SUCCESS: '@@user/LOGIN_SUCCESS',
    LOGOUT: '@@user/LOGOUT',

    // landing
    FETCH_REQUEST: '@@login/FETCH_REQUEST',
    FETCH_FAILURE: '@@login/FETCH_FAILURE',

    // form
    FORM_SUCCESS: '@@form/FORM_SUCCESS',
    FORM_ERROR: '@@form/FORM_ERROR',
    FORM_MESSAGES_CLEAR: '@@form/FORM_MESSAGES_CLEAR',

    // File
    CREATING_NEW_FILE: '@@file/CREATING_NEW_FILE',
    FETCH_FILES_SUCCESS: '@@file/FETCH_FILES_SUCCESS',
    FETCH_FILES_FAILURE: '@@file/FETCH_FILES_FAILURE',
    FETCH_FILE_SUCCESS: '@@file/FETCH_FILE_SUCCESS',
    FETCH_FILE_FAILURE: '@@file/FETCH_FILE_FAILURE',
    UPDATE_FILE_SUCCESS: '@@file/UPDATE_FILE_SUCCESS',
    UPDATE_FILE_FAILURE: '@@file/UPDATE_FILE_FAILURE',
    CREATE_FILE_SUCCESS: '@@file/CREATE_FILE_SUCCESS',
    CREATE_FILE_FAILURE: '@@file/CREATE_FILE_FAILURE',

    FETCH_SHARES_SUCCESS: '@@shares/FETCH_SHARES_SUCCESS',
    FETCH_SHARES_FAILURE: '@@shares/FETCH_SHARES_FAILURE',
    FETCH_SHARE_FILE_SUCCESS: '@@shares_file/FETCH_SHARE_FILE_SUCCESS',
    FETCH_SHARE_FILE_FAILURE: '@@shares_file/FETCH_SHARE_FILE_FAILURE',
    SHARE_FILE_SUCCESS: '@@shares_file/SHARE_FILE_SUCCESS',
    SHARE_FILE_FAILURE: '@@shares_file/SHARE_FILE_FAILURE',
    FETCH_PDF_SUCCESS: '@@file/FETCH_FILE_SUCCESS',
    FETCH_PDF_FAILURE: '@@file/FETCH_FILE_FAILURE',

    DOWNLOAD_PDF_SUCCESS: '@@file/DOWNLOAD_PDF_SUCCESS',
    DOWNLOAD_PDF_FAILURE: '@@file/DOWNLOAD_PDF_FAILURE',


    // selected file
    SELECT_FILE: '@@selected_file/SELECT_FILE',
    SAVE_FILE: '@@selected_file/SAVE_FILE',
    ADD_BLOCK_TO_SELECTED_FILE: '@@selected_file/ADD_BLOCK_TO_SELECTED_FILE',
    REMOVE_BLOCK_FROM_SELECTED_FILE: '@@selected_file/REMOVE_BLOCK_FROM_SELECTED_FILE',
    MOVE_BLOCK_FROM_SELECTED_FILE: '@@selected_file/MOVE_BLOCK_FROM_SELECTED_FILE',

    // Comment
    CREATE_COMMENT_SUCCESS: '@@file/CREATE_COMMENT_SUCCESS',
    RECEIVE_COMMENT: '@@file/RECEIVE_COMMENT',


    //Notifcation
    FETCH_NOTIFICATION_SUCCESS: '@@notification/FETCH_NOTIFICATION_SUCCESS',
    SEND_NOTIFICATION_SUCCESS: '@@notification/SEND_NOTIFICATION_SUCCESS',
    RECEIVE_NOTIFICATION: '@@notification/RECIEVE_NOTIFICATION',
    RESOLVE_NOTIFICATION: '@@notification/RESOLVE_NOTIFCATION',

    // Block
    FETCH_BLOCKS_SUCCESS: '@@block/FETCH_BLOCKS_SUCCESS',
    FETCH_BLOCKS_FALURE: '@@block/FETCH_BLOCKS_FALURE',
    CREATE_BLOCK_SUCCESS: '@@block/CREATE_BLOCK_SUCCESS',
    CREATE_BLOCK_FALURE: '@@block/CREATE_BLOCK_FALURE',
    EDIT_BLOCK_SUCCESS: '@@block/EDIT_BLOCK_SUCCESS',
    EDIT_BLOCK_FALURE: '@@block/EDIT_BLOCK_FALURE',

    // Tracking
    FETCH_TRACKING_SUCCESS: '@@tracking/FETCH_TRACKING_SUCCESS',
    FETCH_TRACKING_FAILURE: '@@tracking/FETCH_TRACKING_FAILURE',
    CREATE_TRACKING_SUCCESS: '@@tracking/CREATE_TRACKING_SUCCESS',
    CREATE_TRACKING_FAILURE: '@@tracking/CREATE_TRACKING_FAILURE',
}
